package:
  name: numpy
  version: 2.2.3
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  url: https://files.pythonhosted.org/packages/source/n/numpy/numpy-2.2.3.tar.gz
  sha256: dbdc15f0c81611925f382dfa97b3bd0bc2c1ce19d4fe50482cb0ddc12ba30020

build:
  # numpy uses vendored meson, so we need to pass the cross file manually
  backend-flags: |
    setup-args=-Dallow-noblas=true
    setup-args=--cross-file=${MESON_CROSS_FILE}
  # numpy creates numpy/distutils/__pycache__ directory during the build.
  # It breaks our test because there is a .pyc in the directory.
  post: |
    rm -rf numpy/distutils/__pycache__
  cflags: |
    -Wno-return-type
  cross-build-env: true
  cross-build-files:
    - numpy/_core/include/numpy/numpyconfig.h
    - numpy/_core/include/numpy/_numpyconfig.h
    - numpy/_core/lib/libnpymath.a
    - numpy/random/lib/libnpyrandom.a
about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD-3-Clause
