package:
  name: geos
  version: 3.13.1
  tag:
    - library
source:
  url: https://github.com/libgeos/geos/releases/download/3.13.1/geos-3.13.1.tar.bz2
  sha256: df2c50503295f325e7c8d7b783aca8ba4773919cde984193850cf9e361dfd28c

build:
  type: shared_library
  script: |
    LDFLAGS="${SIDE_MODULE_LDFLAGS}" emcmake cmake \
      -DDISABLE_GEOS_INLINE=ON \
      -DBUILD_TESTING=OFF \
      -DBUILD_BENCHMARKS=OFF \
      -DBUILD_DOCUMENTATION=OFF \
      -DBUILD_GEOSOP=OFF \
      -DCMAKE_C_FLAGS="-fPIC" \
      -DCMAKE_CXX_FLAGS="-fPIC" \
      -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
      ./

    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install

    mkdir -p dist
    cp ${WASM_LIBRARY_DIR}/lib/libgeos* dist/
