package:
  name: numpy-tests
  # keep in sync with numpy-tests
  version: 2.2.3
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  url: https://files.pythonhosted.org/packages/source/n/numpy/numpy-2.2.3.tar.gz
  sha256: dbdc15f0c81611925f382dfa97b3bd0bc2c1ce19d4fe50482cb0ddc12ba30020

build:
  # build under recipes/numpy_shared_build (one level back)
  # to make use of build caching
  directory: ../numpy_shared_build
  unvendor-tests: false
  # numpy uses vendored meson, so we need to pass the cross file manually
  backend-flags: |
    setup-args=-Dallow-noblas=true
    setup-args=--cross-file=${MESON_CROSS_FILE}
    install-args=--tags=tests
    build-dir=build
  # numpy creates numpy/distutils/__pycache__ directory during the build.
  # It breaks our test because there is a .pyc in the directory.

  # Replace name = "numpy" with name = "numpy-tests" in pyproject.toml
  script: |
    sed -i 's/name = "numpy"/name = "numpy-tests"/' pyproject.toml
  post: |
    rm -rf numpy/distutils/__pycache__
  cflags: |
    -Wno-return-type
requirements:
  host:
    - numpy
  run:
    - numpy
about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD-3-Clause
