package:
  name: f2py-example
  version: 0.1.0
  top-level:
    - f2py_example

source:
  path: source

build:
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
  script: |
    git clone https://github.com/hoodmane/f2c.git --depth 1
    (cd f2c/src && cp makefile.u makefile && sed -i "s/gram.c:/gram.c1:/" makefile && make)
    export F2C_PATH=$(pwd)/f2c/src/f2c
    cp f2c/f2c.h ${WASM_LIBRARY_DIR}/include/f2c.h

requirements:
  host:
    - numpy
  run:
    - numpy
  executable:
    - gfortran

about:
  home: https://github.com/pyodide/pyodide-build
  summary: Minimal Fortran/f2py integration test (Fibonacci, loosely based on github.com/larsbuntemeyer/pyfort)
  license: MIT

extra:
  recipe-maintainers:
    - agriyakhetarpal
